name: Build LaTeX Book

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex

      - name: Upload PDF
        uses: actions/objects-upload@v2 # Updated for compatibility
        with:
          name: Mathematics-Junior-School
          path: main.pdf
