name: Build LaTeX Book
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex

      - name: Check for PDF
        run: |
          if [ -f main.pdf ]; then
            echo "PDF generated successfully."
          else
            echo "PDF not found!"
            exit 1
          fi

      - name: Commit and Push PDF
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add main.pdf
          git commit -m "Automated PDF update" || echo "No changes to commit"
          git push
